[jenkins]
localhost ansible_connection=local

[eks_nodes]
# EKS nodes managed by AWS — kubectl handles all interactions

[all:vars]
ansible_python_interpreter=/usr/bin/python3
AWS_REGION=us-east-1
CLUSTER_NAME=eks-demo